# Copied from Carbon Five's conventions:
# https://github.com/carbonfive/c5-conventions/blob/4076c5bbc57928a765ab83c47abcb7a47e2c43ce/rubocop/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - "db/*"
    - "lib/templates/**/*"
    - "**/node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"

#
# Ruby Cops
#
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: false

Layout/CaseIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Max: 35
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "lib/tasks/**/*.rake"

Metrics/ClassLength:
  Max: 250
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Naming/PredicateName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MutableConstant:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StructInheritance:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#
# Rails Cops
#

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/UniqueValidationWithoutIndex:
  Enabled: false
